---
# Tasks for adding Docker GPG key and repository
- name: Ensure prerequisites are installed
  ansible.builtin.package:
    name: "{{ prerequisite_packages }}"
    state: present
  become: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: "{{ keyring_path }}"
    state: directory
    mode: '0755'
  become: true

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ app_url }}"
    dest: "{{ key_final_destination }}"
    mode: '0644'
  become: true

- name: Set proper permissions on GPG key
  ansible.builtin.file:
    path: "{{ key_final_destination }}"
    mode: 'a+r'
  become: true

- name: Add Docker repository to sources list
  ansible.builtin.copy:
    content: "{{ sourcelist_content }}"
    dest: "{{ sourcelist_destination }}"
    mode: '0644'
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true